[package]
name = "part-6"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
common = { path = "../common" }
part-5 = { path = "../part-5" }
rayon = "1.10.0"
serial_test = "3.0.0"
